# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "cylinder_asym"

  output_shape:
    - 480
    - 360
    - 32

  fea_dim: 9
  out_fea_dim: 256
  num_class: 20
  num_input_features: 16
  use_norm: True
  init_size: 32


###################
## Dataset options
dataset_params:
  dataset_type: "cylinder_dataset"
  pc_dataset_type: "SemKITTI_sk"
  ignore_label: 0
  return_test: False
  fixed_volume_space: True
  label_mapping: "./config/label_mapping/semantic-kitti.yaml"
  max_volume_space:
    - 50
    - 3.1415926
    - 2
  min_volume_space:
    - 0
    - -3.1415926
    - -4


###################
## Data_loader options
train_data_loader:
  data_path: "/storage/data/wudj/dataset/SemanticKITTI/kitti/data/sequences"
  imageset: "train"
  return_ref: True
  batch_size: 10
  shuffle: True
  num_workers: 10

val_data_loader:
  data_path: "/storage/data/wudj/dataset/SemanticKITTI/kitti/data/sequences"
  imageset: "val"
  return_ref: True
  batch_size: 6
  shuffle: False
  num_workers: 10


###################
## Train params
train_params:
  gpus:
    - 0
    - 1
  logdir: "/public/home/wudj/Cylinder3D_spconv_v2/logs_test"
  max_num_epochs: 40
  checkpoint_every_n_epochs: 0.5
  base_lr: 0.000707
  weight_decay: 0.001
  mixed_fp16: True
